import { z } from 'zod';
import { ProductTag } from '@/types';

/**
 * Restaurant settings form validation
 */
export const restaurantSchema = z.object({
    name: z
        .string()
        .min(1, 'Restaurant name is required')
        .max(100, 'Name must be less than 100 characters'),
    description: z.string().max(500, 'Description must be less than 500 characters').optional(),
    logoUrl: z.string().url('Must be a valid URL').optional().or(z.literal('')),
    currency: z.enum(['TRY', 'USD', 'EUR']),
});

export type RestaurantFormData = z.infer<typeof restaurantSchema>;

/**
 * Menu form validation
 */
export const menuSchema = z.object({
    name: z
        .string()
        .min(1, 'Menu name is required')
        .max(100, 'Name must be less than 100 characters'),
    orderValue: z.number().int().min(1).optional(),
    isActive: z.boolean(),
    restaurantId: z.string().optional(), // Will be set automatically
});

export type MenuFormData = z.infer<typeof menuSchema>;

/**
 * Category form validation
 */
export const categorySchema = z.object({
    name: z
        .string()
        .min(1, 'Category name is required')
        .max(100, 'Name must be less than 100 characters'),
    description: z.string().max(300, 'Description must be less than 300 characters').optional(),
    imageUrl: z.string().url('Must be a valid URL').optional().or(z.literal('')),
    menuId: z.string().min(1, 'Menu ID is required'),
});

export type CategoryFormData = z.infer<typeof categorySchema>;

/**
 * Product form validation
 */
export const productSchema = z.object({
    name: z
        .string()
        .min(1, 'Product name is required')
        .max(100, 'Name must be less than 100 characters'),
    description: z.string().max(500, 'Description must be less than 500 characters').optional(),
    price: z
        .number()
        .min(0, 'Price must be 0 or greater')
        .max(999999, 'Price is too high'),
    imageUrl: z.string().optional(),
    position: z.string().optional(), // Auto-generated by backend
    categoryId: z.string().min(1, 'Category ID is required'),
    menuId: z.string().optional(), // For Firestore operations
    tags: z.array(z.nativeEnum(ProductTag)).optional(),
    available: z.boolean().optional(),
    active: z.boolean().optional(),
    presence: z.record(z.string(), z.array(z.string())).optional(),
    variations: z.array(z.object({
        type: z.enum(['porsiyon', 'boy', 'gramaj', 'adet', 'ozel']),
        unit: z.string().min(1, 'Birim seçilmeli veya girilmelidir'),
        price: z.number().min(0, 'Fiyat 0 veya daha büyük olmalıdır'),
    })).optional(),
    calories: z.number().min(0).optional(),
    cookingTime: z.number().min(0).optional(),
    allergens: z.array(z.string()).optional(),
});

export type ProductFormData = z.infer<typeof productSchema>;


